CREATE TABLE `workspace_journeys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`currentStep` enum('survey','floor_plan','generating','report_ready','signup_prompted','converted') NOT NULL DEFAULT 'survey',
	`companyName` varchar(200),
	`contactName` varchar(100),
	`contactEmail` varchar(320),
	`contactPhone` varchar(50),
	`employeeCount` int,
	`officeSizePyeong` int,
	`workStyle` enum('collaborative','focused','hybrid','flexible'),
	`remoteWorkRatio` int,
	`meetingFrequency` enum('rarely','few_weekly','daily','very_frequent'),
	`painPoints` json,
	`desiredSpaces` json,
	`designStyle` enum('modern','minimal','warm','industrial','natural','luxury','creative'),
	`budgetRange` varchar(50),
	`priority` enum('design','functionality','cost','balanced'),
	`timelineUrgency` enum('flexible','within_6months','within_3months','urgent'),
	`additionalNotes` text,
	`surveyCompletedAt` timestamp,
	`floorPlanType` enum('blank_template','existing_upload','skipped'),
	`floorPlanFileKey` varchar(500),
	`floorPlanFileUrl` varchar(1000),
	`floorPlanFileName` varchar(300),
	`blankTemplateType` varchar(50),
	`floorPlanAnalysis` json,
	`floorPlanUploadedAt` timestamp,
	`interviewQuestions` json,
	`analysisSummary` text,
	`aiGeneratedAt` timestamp,
	`reportToken` varchar(64),
	`reportPdfKey` varchar(500),
	`reportPdfUrl` varchar(1000),
	`reportEmailSentAt` timestamp,
	`reportViewedAt` timestamp,
	`companySurveyToken` varchar(64),
	`companySurveyResponseCount` int DEFAULT 0,
	`clientId` int,
	`convertedAt` timestamp,
	`utmSource` varchar(100),
	`utmMedium` varchar(100),
	`utmCampaign` varchar(100),
	`referrer` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workspace_journeys_id` PRIMARY KEY(`id`),
	CONSTRAINT `workspace_journeys_sessionId_unique` UNIQUE(`sessionId`)
);
