CREATE TABLE `design_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(300) NOT NULL,
	`clientId` int,
	`crmDealId` int,
	`companyName` varchar(200),
	`contactName` varchar(100),
	`contactEmail` varchar(320),
	`contactPhone` varchar(30),
	`stage` enum('floorplan','rfp','analysis','layout','rendering','proposal','estimate','completed') NOT NULL DEFAULT 'floorplan',
	`status` enum('active','paused','completed','archived') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `design_projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `detailed_estimates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`proposalId` int,
	`version` int DEFAULT 1,
	`title` varchar(300) NOT NULL,
	`items` json,
	`subtotal` int,
	`vat` int,
	`totalAmount` int,
	`optionItems` json,
	`pdfUrl` text,
	`excelUrl` text,
	`notes` text,
	`validUntil` timestamp,
	`status` enum('draft','generating','review','final','sent') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `detailed_estimates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `floor_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`fileUrl` text NOT NULL,
	`fileKey` varchar(500),
	`fileName` varchar(300),
	`fileType` varchar(50),
	`fileSize` int,
	`totalArea` varchar(50),
	`floors` int,
	`roomCount` int,
	`aiAnalysis` json,
	`analysisStatus` enum('pending','analyzing','done','error') NOT NULL DEFAULT 'pending',
	`analysisError` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `floor_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `layout_options` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`optionName` varchar(100) NOT NULL,
	`concept` text,
	`layoutImageUrl` text,
	`layoutData` json,
	`spaceAllocation` json,
	`pros` json,
	`cons` json,
	`aiScore` int,
	`isSelected` enum('yes','no') NOT NULL DEFAULT 'no',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `layout_options_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`version` int DEFAULT 1,
	`title` varchar(300) NOT NULL,
	`clientAnalysis` json,
	`designConcept` text,
	`spaceProgram` json,
	`materialPlan` json,
	`furniturePlan` json,
	`projectTimeline` json,
	`companyIntro` text,
	`differentiators` json,
	`pdfUrl` text,
	`pptUrl` text,
	`status` enum('draft','generating','review','final') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `renderings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`layoutId` int,
	`spaceType` varchar(100) NOT NULL,
	`spaceName` varchar(200),
	`prompt` text,
	`imageUrl` text,
	`thumbnailUrl` text,
	`style` varchar(100),
	`status` enum('pending','generating','done','error') NOT NULL DEFAULT 'pending',
	`error` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `renderings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rfp_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`collectionMethod` enum('form','ai_generator','chatbot') NOT NULL DEFAULT 'form',
	`companyName` varchar(200),
	`industry` varchar(100),
	`foundedYear` int,
	`projectType` enum('new_office','relocation','renovation','expansion'),
	`currentAddress` text,
	`newAddress` text,
	`totalArea` varchar(50),
	`currentHeadcount` int,
	`plannedHeadcount1y` int,
	`plannedHeadcount3y` int,
	`departments` json,
	`spaceRequirements` json,
	`preferredStyle` varchar(100),
	`brandColors` json,
	`brandGuidelineUrl` text,
	`referenceImages` json,
	`referenceUrls` json,
	`preferredMaterials` json,
	`lightingPreference` varchar(200),
	`avItRequirements` text,
	`networkInfra` text,
	`securitySystem` text,
	`acousticPrivacy` varchar(100),
	`hvacRequirements` text,
	`esgRequirements` text,
	`budgetRange` varchar(100),
	`budgetInclDesign` enum('yes','no','separate'),
	`priorityOrder` varchar(200),
	`desiredStartDate` timestamp,
	`desiredEndDate` timestamp,
	`occupiedDuringWork` enum('yes','no','partial'),
	`buildingRestrictions` text,
	`reuseExistingFurniture` enum('yes','no','partial'),
	`specialRequests` text,
	`competitorBenchmarks` text,
	`aiSummary` text,
	`completionRate` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rfp_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tour_videos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`title` varchar(300),
	`videoUrl` text,
	`thumbnailUrl` text,
	`duration` int,
	`renderingIds` json,
	`status` enum('pending','generating','done','error') NOT NULL DEFAULT 'pending',
	`error` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tour_videos_id` PRIMARY KEY(`id`)
);
