CREATE TABLE `portfolio_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`portfolioId` int NOT NULL,
	`reviewerName` varchar(100) NOT NULL,
	`reviewerTitle` varchar(100),
	`reviewerCompany` varchar(200),
	`reviewerEmail` varchar(320),
	`reviewerPhone` varchar(30),
	`reviewerPhotoUrl` text,
	`rating` int,
	`title` varchar(300),
	`content` text,
	`highlights` json,
	`accessToken` varchar(64) NOT NULL,
	`tokenExpiresAt` timestamp,
	`status` enum('pending','submitted','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNote` text,
	`approvedAt` timestamp,
	`submittedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portfolio_reviews_id` PRIMARY KEY(`id`),
	CONSTRAINT `portfolio_reviews_accessToken_unique` UNIQUE(`accessToken`)
);
