export const ENV = {
  appId: process.env.VITE_APP_ID ?? "kokamdo",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  masterEmail: process.env.MASTER_EMAIL ?? "henrykkim@kokamdo.co.kr",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI ?? "",
  naverClientId: process.env.NAVER_CLIENT_ID ?? "",
  naverClientSecret: process.env.NAVER_CLIENT_SECRET ?? "",
  naverRedirectUri: process.env.NAVER_REDIRECT_URI ?? "",
  kakaoClientId: process.env.KAKAO_CLIENT_ID ?? "",
  kakaoClientSecret: process.env.KAKAO_CLIENT_SECRET ?? "",
  kakaoRedirectUri: process.env.KAKAO_REDIRECT_URI ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  // 예약 작업(스케줄러)이 무인 API 호출 시 사용하는 공유 시크릿
  scheduledTaskSecret: process.env.SCHEDULED_TASK_SECRET ?? "",
};
