/**
 * 확장 테이블 생성 (CRM / OpsX / 설문 / KPI / 사후관리 등)
 *
 * schema.ts에는 정의돼 있으나 마이그레이션·ensureTables() 어디에도 없어
 * 프로덕션 DB에 생성되지 않았던 103개 테이블을 부팅 시 멱등 생성한다.
 * 출처: drizzle-kit generate(schema.ts)에서 기존 15개 테이블을 제외한 신규만 추출 (2026-07-21).
 *
 * 각 문장을 개별 try/catch로 실행해 하나가 실패해도 나머지는 계속 생성한다.
 * 모두 CREATE TABLE IF NOT EXISTS 이므로 기존 테이블/데이터는 건드리지 않는다.
 */
import type { Connection } from "mysql2/promise";

const EXTENDED_TABLE_DDL: string[] = [
  "CREATE TABLE IF NOT EXISTS `activity_logs` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`userId` int NOT NULL,\n\t`userName` varchar(200),\n\t`action` varchar(100) NOT NULL,\n\t`target` varchar(200),\n\t`details` text,\n\t`ipAddress` varchar(50),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `activity_logs_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ai_redesigns` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`originalImageUrl` text NOT NULL,\n\t`prompt` text NOT NULL,\n\t`resultImageUrl` text,\n\t`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',\n\t`errorMessage` text,\n\t`customerName` varchar(100),\n\t`customerEmail` varchar(320),\n\t`customerPhone` varchar(30),\n\t`spaceType` varchar(50),\n\t`userIp` varchar(45),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ai_redesigns_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ai_reports` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`type` enum('analysis','proposal') NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`content` longtext NOT NULL,\n\t`summary` text,\n\t`emailSentAt` timestamp,\n\t`emailSentTo` varchar(320),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ai_reports_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `attendance_records` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`userId` int NOT NULL,\n\t`clockInAt` timestamp NOT NULL,\n\t`clockOutAt` timestamp,\n\t`workType` enum('office','site','remote','half_day') NOT NULL DEFAULT 'office',\n\t`siteName` varchar(200),\n\t`memo` text,\n\t`totalMinutes` int,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `attendance_records_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `auto_email_logs` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientProjectId` int,\n\t`recipientEmail` varchar(320) NOT NULL,\n\t`recipientName` varchar(200),\n\t`emailType` enum('initial_survey','survey_reminder','analysis_report','company_survey_link','company_survey_updated','realestate_matches','proposal','post_occupancy','optimization_report') NOT NULL,\n\t`subject` varchar(500) NOT NULL,\n\t`status` enum('queued','sent','delivered','failed','bounced') NOT NULL DEFAULT 'queued',\n\t`metadata` json,\n\t`sentAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `auto_email_logs_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `chat_sessions` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`sessionId` varchar(64) NOT NULL,\n\t`messages` json,\n\t`contactEmail` varchar(320),\n\t`contactName` varchar(100),\n\t`contactPhone` varchar(30),\n\t`summary` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `chat_sessions_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `chat_sessions_sessionId_unique` UNIQUE(`sessionId`)\n)",
  "CREATE TABLE IF NOT EXISTS `client_floor_plans` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`fileName` varchar(500) NOT NULL,\n\t`fileUrl` text NOT NULL,\n\t`fileKey` varchar(500) NOT NULL,\n\t`fileType` varchar(50) NOT NULL,\n\t`fileSize` int,\n\t`floorNumber` int,\n\t`floorName` varchar(100),\n\t`totalArea` decimal(10,2),\n\t`aiAnalysis` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `client_floor_plans_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `client_notifications` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientId` int NOT NULL,\n\t`projectId` int,\n\t`type` enum('status_change','meeting_confirmed','meeting_cancelled','report_ready','survey_complete','system') NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`message` text NOT NULL,\n\t`linkUrl` varchar(500),\n\t`metadata` json,\n\t`isRead` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `client_notifications_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `client_projects` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`userId` int NOT NULL,\n\t`companyName` varchar(200) NOT NULL,\n\t`contactName` varchar(100) NOT NULL,\n\t`contactEmail` varchar(320) NOT NULL,\n\t`contactPhone` varchar(30),\n\t`employeeCount` int,\n\t`currentAddress` text,\n\t`desiredMoveDate` varchar(50),\n\t`budgetRange` varchar(100),\n\t`status` enum('created','floor_plan_uploaded','survey_completed','report_generated','report_sent','company_survey_shared','company_survey_done','meeting_requested','meeting_confirmed','completed') NOT NULL DEFAULT 'created',\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `client_projects_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `clients_auth` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`email` varchar(320) NOT NULL,\n\t`passwordHash` varchar(255) NOT NULL,\n\t`name` varchar(100) NOT NULL,\n\t`company` varchar(200),\n\t`phone` varchar(20),\n\t`emailVerified` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`emailVerifyToken` varchar(64),\n\t`emailVerifyExpires` timestamp,\n\t`passwordResetToken` varchar(64),\n\t`passwordResetExpires` timestamp,\n\t`status` enum('active','suspended','pending') NOT NULL DEFAULT 'pending',\n\t`assignedProjectIds` json,\n\t`lastLoginAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `clients_auth_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `clients_auth_email_unique` UNIQUE(`email`)\n)",
  "CREATE TABLE IF NOT EXISTS `company_survey_responses` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`surveyId` int NOT NULL,\n\t`department` varchar(100),\n\t`role` varchar(100),\n\t`tenure` enum('less_1y','1_3y','3_5y','5_10y','over_10y'),\n\t`overallSatisfaction` int,\n\t`noiseSatisfaction` int,\n\t`lightingSatisfaction` int,\n\t`temperatureSatisfaction` int,\n\t`spaceSatisfaction` int,\n\t`privacySatisfaction` int,\n\t`deskUsageHours` int,\n\t`meetingHoursPerDay` decimal(3,1),\n\t`collaborationFrequency` enum('rarely','sometimes','often','always'),\n\t`focusWorkNeed` enum('low','medium','high','critical'),\n\t`desiredSpaces` json,\n\t`improvementSuggestions` text,\n\t`additionalComments` text,\n\t`submittedAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `company_survey_responses_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `company_wide_surveys` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`token` varchar(64) NOT NULL,\n\t`title` varchar(200) NOT NULL,\n\t`description` text,\n\t`expiresAt` timestamp,\n\t`maxResponses` int,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`responseCount` int NOT NULL DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `company_wide_surveys_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `company_wide_surveys_token_unique` UNIQUE(`token`)\n)",
  "CREATE TABLE IF NOT EXISTS `crm_activities` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`dealId` int,\n\t`clientId` int,\n\t`type` enum('stage_change','note','task','file_upload','email_sent','call_logged','meeting_scheduled') NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`description` text,\n\t`metadata` json,\n\t`createdBy` varchar(100),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `crm_activities_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `crm_clients` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`companyName` varchar(200) NOT NULL,\n\t`contactName` varchar(100) NOT NULL,\n\t`contactTitle` varchar(100),\n\t`email` varchar(320),\n\t`phone` varchar(30),\n\t`address` text,\n\t`industry` varchar(100),\n\t`companySize` varchar(50),\n\t`source` enum('website','referral','cold_call','exhibition','sns','other') DEFAULT 'website',\n\t`notes` text,\n\t`tags` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `crm_clients_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `crm_deals` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientId` int NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`stage` enum('lead','consultation','proposal','negotiation','contract','design','construction','completed','lost') NOT NULL DEFAULT 'lead',\n\t`estimatedValue` int,\n\t`actualValue` int,\n\t`area` varchar(50),\n\t`spaceType` enum('office','commercial','medical','education','residential','other'),\n\t`startDate` timestamp,\n\t`expectedEndDate` timestamp,\n\t`actualEndDate` timestamp,\n\t`assignedTo` varchar(100),\n\t`probability` int,\n\t`description` text,\n\t`lostReason` text,\n\t`tags` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `crm_deals_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `crm_interactions` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientId` int NOT NULL,\n\t`type` enum('phone_call','email','meeting','site_visit','video_call','kakao','note') NOT NULL,\n\t`subject` varchar(300) NOT NULL,\n\t`content` text,\n\t`outcome` text,\n\t`nextAction` text,\n\t`nextActionDate` timestamp,\n\t`assignedTo` varchar(100),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `crm_interactions_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `daily_site_reports` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`authorId` int NOT NULL,\n\t`reportDate` varchar(20) NOT NULL,\n\t`weather` varchar(50),\n\t`temperature` varchar(20),\n\t`workersInternal` int DEFAULT 0,\n\t`workersExternal` int DEFAULT 0,\n\t`workerDetails` json,\n\t`workCompleted` text NOT NULL,\n\t`workPlanned` text,\n\t`materialsReceived` json,\n\t`safetyChecklist` json,\n\t`qualityIssues` text,\n\t`specialNotes` text,\n\t`clientRequests` text,\n\t`photoUrls` json,\n\t`overallProgress` int,\n\t`scheduleStatus` enum('on_track','ahead','delayed') DEFAULT 'on_track',\n\t`status` enum('draft','submitted','reviewed','approved') NOT NULL DEFAULT 'draft',\n\t`reviewedBy` int,\n\t`reviewedAt` timestamp,\n\t`reviewNotes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `daily_site_reports_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `deletion_logs` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`tableName` varchar(100) NOT NULL,\n\t`recordId` int NOT NULL,\n\t`recordData` json NOT NULL,\n\t`deletedByUserId` int NOT NULL,\n\t`deletedByUserName` varchar(200),\n\t`reason` text,\n\t`restored` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`restoredByUserId` int,\n\t`restoredAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `deletion_logs_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `design_projects` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`clientId` int,\n\t`crmDealId` int,\n\t`companyName` varchar(200),\n\t`contactName` varchar(100),\n\t`contactEmail` varchar(320),\n\t`contactPhone` varchar(30),\n\t`stage` enum('floorplan','rfp','analysis','layout','rendering','proposal','estimate','completed') NOT NULL DEFAULT 'floorplan',\n\t`status` enum('active','paused','completed','archived') NOT NULL DEFAULT 'active',\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `design_projects_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `detailed_estimates` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`proposalId` int,\n\t`version` int DEFAULT 1,\n\t`title` varchar(300) NOT NULL,\n\t`items` json,\n\t`subtotal` int,\n\t`vat` int,\n\t`totalAmount` int,\n\t`optionItems` json,\n\t`pdfUrl` text,\n\t`excelUrl` text,\n\t`notes` text,\n\t`validUntil` timestamp,\n\t`status` enum('draft','generating','review','final','sent') NOT NULL DEFAULT 'draft',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `detailed_estimates_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `download_logs` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`userId` int,\n\t`userName` varchar(255),\n\t`userEmail` varchar(255),\n\t`fileType` enum('estimate_pdf','expense_pdf','project_report_pdf','proposal_pdf','lead_magnet','ai_estimate_result','design_auto_result','other') NOT NULL,\n\t`fileName` varchar(500),\n\t`projectId` int,\n\t`projectName` varchar(255),\n\t`trackingCode` varchar(64) NOT NULL,\n\t`ipAddress` varchar(45),\n\t`userAgent` text,\n\t`consentGiven` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `download_logs_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `drive_sync_log` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`folderId` varchar(200) NOT NULL,\n\t`folderPath` varchar(500),\n\t`fileCount` int DEFAULT 0,\n\t`draftId` int,\n\t`syncStatus` enum('syncing','done','error') NOT NULL DEFAULT 'syncing',\n\t`lastSyncAt` timestamp NOT NULL DEFAULT (now()),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `drive_sync_log_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `field_measurement_sessions` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectName` varchar(200) NOT NULL,\n\t`location` varchar(500),\n\t`description` text,\n\t`opsProjectId` int,\n\t`clientProjectId` int,\n\t`createdBy` int,\n\t`createdByName` varchar(100),\n\t`status` enum('active','completed','archived') NOT NULL DEFAULT 'active',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `field_measurement_sessions_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `field_measurements` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`panoramaId` int NOT NULL,\n\t`sessionId` int NOT NULL,\n\t`type` enum('distance','height','area','reference') NOT NULL DEFAULT 'distance',\n\t`label` varchar(200),\n\t`points` json NOT NULL,\n\t`rawAngle` decimal(10,6),\n\t`calibratedValue` decimal(10,3),\n\t`unit` varchar(10) DEFAULT 'm',\n\t`isReference` boolean DEFAULT false,\n\t`referenceRealValue` decimal(10,3),\n\t`note` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `field_measurements_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `floor_plans` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`fileUrl` text NOT NULL,\n\t`fileKey` varchar(500),\n\t`fileName` varchar(300),\n\t`fileType` varchar(50),\n\t`fileSize` int,\n\t`totalArea` varchar(50),\n\t`floors` int,\n\t`roomCount` int,\n\t`aiAnalysis` json,\n\t`analysisStatus` enum('pending','analyzing','done','error') NOT NULL DEFAULT 'pending',\n\t`analysisError` text,\n\t`sortOrder` int DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `floor_plans_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `kpi_definitions` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`description` text,\n\t`category` varchar(100),\n\t`department` varchar(100),\n\t`measureUnit` varchar(50),\n\t`targetValue` decimal(15,2),\n\t`weight` int DEFAULT 100,\n\t`frequency` enum('daily','weekly','monthly','quarterly','yearly') NOT NULL DEFAULT 'monthly',\n\t`calculationMethod` enum('manual','auto_count','auto_sum','auto_avg','formula') NOT NULL DEFAULT 'manual',\n\t`autoQuery` text,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `kpi_definitions_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `kpi_records` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`kpiId` int NOT NULL,\n\t`userId` int NOT NULL,\n\t`period` varchar(20) NOT NULL,\n\t`targetValue` decimal(15,2),\n\t`actualValue` decimal(15,2),\n\t`achievementRate` decimal(5,2),\n\t`notes` text,\n\t`evidence` json,\n\t`status` enum('pending','submitted','approved','rejected') NOT NULL DEFAULT 'pending',\n\t`approvedBy` int,\n\t`approvedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `kpi_records_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `layout_options` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`optionName` varchar(100) NOT NULL,\n\t`concept` text,\n\t`layoutImageUrl` text,\n\t`layoutData` json,\n\t`spaceAllocation` json,\n\t`pros` json,\n\t`cons` json,\n\t`aiScore` int,\n\t`isSelected` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `layout_options_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `lead_downloads` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`email` varchar(320) NOT NULL,\n\t`name` varchar(100),\n\t`company` varchar(200),\n\t`resourceId` varchar(50) NOT NULL,\n\t`resourceTitle` varchar(200),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `lead_downloads_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `leave_requests` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`userId` int NOT NULL,\n\t`leaveType` enum('annual','half_am','half_pm','sick','special','other') NOT NULL,\n\t`startDate` varchar(10) NOT NULL,\n\t`endDate` varchar(10) NOT NULL,\n\t`reason` text,\n\t`leaveStatus` enum('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',\n\t`approvedBy` int,\n\t`reviewedAt` timestamp,\n\t`reviewComment` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `leave_requests_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `material_price_analytics` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`materialCode` varchar(100) NOT NULL,\n\t`materialName` varchar(300) NOT NULL,\n\t`category` varchar(100),\n\t`avgPrice` decimal(15,0),\n\t`minPrice` decimal(15,0),\n\t`maxPrice` decimal(15,0),\n\t`priceChangeRate` decimal(5,2),\n\t`sampleCount` int DEFAULT 0,\n\t`trendDirection` enum('rising','stable','falling') DEFAULT 'stable',\n\t`aiInsight` text,\n\t`alertLevel` enum('normal','watch','alert') DEFAULT 'normal',\n\t`periodStart` varchar(20),\n\t`periodEnd` varchar(20),\n\t`lastUpdated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `material_price_analytics_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `material_price_history` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`materialCode` varchar(100) NOT NULL,\n\t`materialName` varchar(300) NOT NULL,\n\t`category` varchar(100),\n\t`specification` text,\n\t`unit` varchar(50),\n\t`unitPrice` decimal(15,0) NOT NULL,\n\t`vendorName` varchar(200),\n\t`vendorQuoteId` int,\n\t`projectId` int,\n\t`priceDate` varchar(20) NOT NULL,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `material_price_history_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `measurement_reports` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`sessionId` int NOT NULL,\n\t`totalArea` decimal(10,2),\n\t`roomCount` int,\n\t`spaceSummary` json,\n\t`aiAnalysis` longtext,\n\t`pdfUrl` text,\n\t`pointCloudData` json,\n\t`digitalTwinStatus` enum('none','processing','ready') DEFAULT 'none',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `measurement_reports_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `meeting_bookings` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`requestedDate` varchar(20) NOT NULL,\n\t`requestedTime` varchar(10) NOT NULL,\n\t`duration` int NOT NULL DEFAULT 60,\n\t`meetingType` enum('online','visit','office') NOT NULL DEFAULT 'office',\n\t`location` text,\n\t`agenda` text,\n\t`status` enum('requested','confirmed','rescheduled','cancelled','completed') NOT NULL DEFAULT 'requested',\n\t`confirmedDate` varchar(20),\n\t`confirmedTime` varchar(10),\n\t`adminNotes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `meeting_bookings_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `notifications` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`type` enum('inquiry','estimate','crm_deal','crm_stage_change','newsletter','chat','system') NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`message` text NOT NULL,\n\t`linkUrl` varchar(500),\n\t`metadata` json,\n\t`isRead` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `notifications_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `occupancy_events` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`sensorId` int NOT NULL,\n\t`zoneId` int,\n\t`eventType` enum('enter','exit','count_change') NOT NULL,\n\t`count` int DEFAULT 0,\n\t`eventAt` timestamp NOT NULL,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `occupancy_events_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `okr_key_results` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`objectiveId` int NOT NULL,\n\t`title` varchar(500) NOT NULL,\n\t`measureType` enum('number','percentage','currency','boolean') NOT NULL DEFAULT 'number',\n\t`startValue` decimal(15,2) DEFAULT '0',\n\t`targetValue` decimal(15,2) NOT NULL,\n\t`currentValue` decimal(15,2) DEFAULT '0',\n\t`progress` int DEFAULT 0,\n\t`confidence` enum('on_track','at_risk','off_track') DEFAULT 'on_track',\n\t`notes` text,\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `okr_key_results_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `okr_objectives` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`userId` int NOT NULL,\n\t`parentId` int,\n\t`level` enum('company','department','team','individual') NOT NULL DEFAULT 'individual',\n\t`title` varchar(500) NOT NULL,\n\t`description` text,\n\t`period` varchar(20) NOT NULL,\n\t`progress` int DEFAULT 0,\n\t`status` enum('draft','active','completed','cancelled') NOT NULL DEFAULT 'draft',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `okr_objectives_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_approval_lines` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(200) NOT NULL,\n\t`documentType` enum('expense','contract','estimate','general') NOT NULL DEFAULT 'expense',\n\t`steps` json NOT NULL,\n\t`isDefault` tinyint DEFAULT 0,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_approval_lines_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_approval_steps` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`documentType` enum('expense','contract','estimate','general') NOT NULL,\n\t`documentId` int NOT NULL,\n\t`stepOrder` int NOT NULL,\n\t`approverId` int NOT NULL,\n\t`approverName` varchar(100) NOT NULL,\n\t`status` enum('pending','approved','rejected','skipped') NOT NULL DEFAULT 'pending',\n\t`comment` text,\n\t`actionAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ops_approval_steps_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_camera_events` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`cameraId` int NOT NULL,\n\t`eventType` enum('online','offline','snapshot','motion','error') NOT NULL,\n\t`message` text,\n\t`snapshotUrl` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ops_camera_events_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_cameras` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`name` varchar(200) NOT NULL,\n\t`location` varchar(300),\n\t`streamUrl` text,\n\t`rtspUrl` text,\n\t`go2rtcStreamName` varchar(100),\n\t`go2rtcServerUrl` text,\n\t`thumbnailUrl` text,\n\t`isOnline` tinyint DEFAULT 0,\n\t`batteryLevel` int,\n\t`lastOnlineAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_cameras_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_client_invites` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`clientName` varchar(200) NOT NULL,\n\t`clientEmail` varchar(320),\n\t`token` varchar(64) NOT NULL,\n\t`permissions` json,\n\t`expiresAt` timestamp,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`lastAccessedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ops_client_invites_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `ops_client_invites_token_unique` UNIQUE(`token`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_contracts` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`authorId` int NOT NULL,\n\t`contractNumber` varchar(50) NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`contractType` enum('main','subcontract','design','consulting','maintenance','other') NOT NULL DEFAULT 'main',\n\t`partyA` varchar(200) NOT NULL,\n\t`partyB` varchar(200) NOT NULL,\n\t`contractAmount` decimal(15,0),\n\t`startDate` varchar(20),\n\t`endDate` varchar(20),\n\t`paymentTerms` text,\n\t`specialTerms` text,\n\t`fileUrl` text,\n\t`fileKey` varchar(500),\n\t`attachmentUrls` json,\n\t`status` enum('draft','reviewing','signed','active','completed','terminated') NOT NULL DEFAULT 'draft',\n\t`signedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_contracts_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_cost_items` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`category` enum('material','labor','subcontract','equipment','overhead','design','permit','other') NOT NULL,\n\t`subcategory` varchar(200),\n\t`description` varchar(500) NOT NULL,\n\t`budgetAmount` decimal(15,0),\n\t`actualAmount` decimal(15,0),\n\t`paidAmount` decimal(15,0),\n\t`vendor` varchar(200),\n\t`expenseId` int,\n\t`invoiceDate` varchar(20),\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_cost_items_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_estimates` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`authorId` int NOT NULL,\n\t`estimateNumber` varchar(50) NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`version` int DEFAULT 1,\n\t`items` json,\n\t`subtotal` decimal(15,0),\n\t`overhead` decimal(15,0),\n\t`profit` decimal(15,0),\n\t`vat` decimal(15,0),\n\t`grandTotal` decimal(15,0),\n\t`fileUrl` text,\n\t`fileKey` varchar(500),\n\t`notes` text,\n\t`validUntil` varchar(20),\n\t`status` enum('draft','submitted','approved','rejected','sent') NOT NULL DEFAULT 'draft',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_estimates_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_expenses` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`authorId` int NOT NULL,\n\t`approvalLineId` int,\n\t`expenseNumber` varchar(50) NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`category` enum('material','labor','subcontract','equipment','transportation','utility','office','meal','other') NOT NULL DEFAULT 'other',\n\t`items` json NOT NULL,\n\t`totalAmount` decimal(15,0) NOT NULL,\n\t`paymentMethod` enum('bank_transfer','card','cash','check') DEFAULT 'bank_transfer',\n\t`payeeName` varchar(200),\n\t`payeeBank` varchar(100),\n\t`payeeAccount` varchar(50),\n\t`receiptUrls` json,\n\t`attachmentUrls` json,\n\t`notes` text,\n\t`status` enum('draft','submitted','in_review','approved','rejected','paid') NOT NULL DEFAULT 'draft',\n\t`submittedAt` timestamp,\n\t`approvedAt` timestamp,\n\t`paidAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_expenses_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_meeting_notes` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`authorId` int NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`meetingDate` varchar(20) NOT NULL,\n\t`meetingTime` varchar(10),\n\t`location` varchar(200),\n\t`meetingType` enum('internal','client','subcontractor','inspection') NOT NULL DEFAULT 'internal',\n\t`attendees` json,\n\t`agenda` text,\n\t`content` text NOT NULL,\n\t`decisions` json,\n\t`actionItems` json,\n\t`attachmentUrls` json,\n\t`status` enum('draft','finalized') NOT NULL DEFAULT 'draft',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_meeting_notes_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_notifications` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int,\n\t`recipientId` int NOT NULL,\n\t`type` enum('schedule_delay','expense_submitted','expense_approved','expense_rejected','sub_quote_submitted','sub_report_submitted','meeting_scheduled','meeting_reminder','project_status','client_inquiry','approval_pending','general') NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`message` text,\n\t`link` varchar(500),\n\t`isRead` tinyint NOT NULL DEFAULT 0,\n\t`readAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ops_notifications_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_projects` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`code` varchar(50) NOT NULL,\n\t`clientName` varchar(200) NOT NULL,\n\t`clientContact` varchar(100),\n\t`clientEmail` varchar(320),\n\t`clientPhone` varchar(30),\n\t`siteAddress` text,\n\t`totalArea` decimal(10,2),\n\t`contractAmount` decimal(15,0),\n\t`startDate` varchar(20),\n\t`endDate` varchar(20),\n\t`status` enum('planning','designing','permit','construction','inspection','completed','warranty','closed') NOT NULL DEFAULT 'planning',\n\t`managerId` int,\n\t`teamMembers` json,\n\t`description` text,\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_projects_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_schedule_items` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`parentId` int,\n\t`name` varchar(300) NOT NULL,\n\t`category` varchar(100),\n\t`startDate` varchar(20),\n\t`endDate` varchar(20),\n\t`progress` int DEFAULT 0,\n\t`status` enum('not_started','in_progress','delayed','completed','on_hold') NOT NULL DEFAULT 'not_started',\n\t`assignedTo` varchar(200),\n\t`subcontractorId` int,\n\t`sortOrder` int DEFAULT 0,\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_schedule_items_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_sub_evaluations` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`evaluatorId` int NOT NULL,\n\t`qualityScore` int NOT NULL,\n\t`scheduleScore` int NOT NULL,\n\t`safetyScore` int NOT NULL,\n\t`communicationScore` int NOT NULL,\n\t`cleanupScore` int NOT NULL,\n\t`overallScore` decimal(3,1),\n\t`strengths` text,\n\t`improvements` text,\n\t`recommendation` enum('highly_recommended','recommended','neutral','not_recommended') NOT NULL DEFAULT 'neutral',\n\t`comment` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_sub_evaluations_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_sub_invites` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`token` varchar(64) NOT NULL,\n\t`expiresAt` timestamp,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ops_sub_invites_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `ops_sub_invites_token_unique` UNIQUE(`token`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_sub_quotes` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`items` json,\n\t`totalAmount` decimal(15,0),\n\t`fileUrl` text,\n\t`fileKey` varchar(500),\n\t`notes` text,\n\t`status` enum('submitted','reviewing','approved','rejected','revised') NOT NULL DEFAULT 'submitted',\n\t`reviewComment` text,\n\t`reviewedBy` int,\n\t`reviewedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_sub_quotes_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_sub_work_reports` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`reportDate` varchar(20) NOT NULL,\n\t`workDescription` text NOT NULL,\n\t`workersCount` int,\n\t`materialsUsed` text,\n\t`photoUrls` json,\n\t`issues` text,\n\t`status` enum('submitted','acknowledged','approved','rejected') NOT NULL DEFAULT 'submitted',\n\t`approvedBy` int,\n\t`approvedAt` timestamp,\n\t`approvalComment` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `ops_sub_work_reports_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_subcontractors` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`companyName` varchar(200) NOT NULL,\n\t`businessNumber` varchar(20),\n\t`representativeName` varchar(100),\n\t`contactName` varchar(100),\n\t`contactPhone` varchar(30),\n\t`contactEmail` varchar(320),\n\t`specialty` varchar(200),\n\t`bankName` varchar(100),\n\t`bankAccount` varchar(50),\n\t`bankHolder` varchar(100),\n\t`rating` int,\n\t`notes` text,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_subcontractors_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `ops_work_reports` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`authorId` int NOT NULL,\n\t`authorName` varchar(100),\n\t`reportDate` varchar(20) NOT NULL,\n\t`reportType` enum('daily','weekly','special') NOT NULL DEFAULT 'daily',\n\t`title` varchar(300) NOT NULL,\n\t`content` text NOT NULL,\n\t`weatherCondition` varchar(50),\n\t`workersCount` int,\n\t`safetyIssues` text,\n\t`photoUrls` json,\n\t`attachmentUrls` json,\n\t`status` enum('draft','submitted','reviewed') NOT NULL DEFAULT 'draft',\n\t`reviewedBy` int,\n\t`reviewedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `ops_work_reports_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `panorama_images` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`sessionId` int NOT NULL,\n\t`imageUrl` text NOT NULL,\n\t`thumbnailUrl` text,\n\t`spotName` varchar(200) NOT NULL,\n\t`spotOrder` int DEFAULT 0,\n\t`cameraHeight` decimal(6,3),\n\t`calibrationData` json,\n\t`exifData` json,\n\t`imageWidth` int,\n\t`imageHeight` int,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `panorama_images_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `popups` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`title` varchar(200) NOT NULL,\n\t`content` text NOT NULL,\n\t`imageUrl` text,\n\t`linkUrl` varchar(500),\n\t`linkText` varchar(100),\n\t`position` enum('center','bottom_right','bottom_left') NOT NULL DEFAULT 'center',\n\t`showOnce` enum('yes','no') NOT NULL DEFAULT 'no',\n\t`active` enum('yes','no') NOT NULL DEFAULT 'yes',\n\t`priority` int DEFAULT 0,\n\t`startsAt` timestamp,\n\t`endsAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `popups_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `portfolio_reviews` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`portfolioId` int NOT NULL,\n\t`reviewerName` varchar(100) NOT NULL,\n\t`reviewerTitle` varchar(100),\n\t`reviewerCompany` varchar(200),\n\t`reviewerEmail` varchar(320),\n\t`reviewerPhone` varchar(30),\n\t`reviewerPhotoUrl` text,\n\t`rating` int,\n\t`title` varchar(300),\n\t`content` text,\n\t`highlights` json,\n\t`accessToken` varchar(64) NOT NULL,\n\t`tokenExpiresAt` timestamp,\n\t`status` enum('pending','submitted','approved','rejected') NOT NULL DEFAULT 'pending',\n\t`adminNote` text,\n\t`approvedAt` timestamp,\n\t`submittedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `portfolio_reviews_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `portfolio_reviews_accessToken_unique` UNIQUE(`accessToken`)\n)",
  "CREATE TABLE IF NOT EXISTS `program_diagrams` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientProjectId` int NOT NULL,\n\t`realestateMatchId` int,\n\t`floorPlanId` int,\n\t`title` varchar(300) NOT NULL,\n\t`diagramData` json NOT NULL,\n\t`aiAnalysis` text,\n\t`version` int DEFAULT 1,\n\t`isSelected` tinyint DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `program_diagrams_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `proposals` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`version` int DEFAULT 1,\n\t`title` varchar(300) NOT NULL,\n\t`clientAnalysis` json,\n\t`designConcept` text,\n\t`spaceProgram` json,\n\t`materialPlan` json,\n\t`furniturePlan` json,\n\t`projectTimeline` json,\n\t`companyIntro` text,\n\t`differentiators` json,\n\t`pdfUrl` text,\n\t`pptUrl` text,\n\t`status` enum('draft','generating','review','final') NOT NULL DEFAULT 'draft',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `proposals_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `purchase_orders` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`poNumber` varchar(50) NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`items` json,\n\t`estimatedTotal` decimal(15,0),\n\t`requiredDate` varchar(20),\n\t`deliveryAddress` text,\n\t`authorId` int NOT NULL,\n\t`authorName` varchar(100),\n\t`status` enum('draft','rfq_sent','quotes_received','quote_selected','ordered','delivered','cancelled') NOT NULL DEFAULT 'draft',\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `purchase_orders_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `realestate_matches` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`searchCriteriaId` int NOT NULL,\n\t`clientProjectId` int NOT NULL,\n\t`propertyName` varchar(300) NOT NULL,\n\t`address` text NOT NULL,\n\t`totalArea` decimal(10,2),\n\t`usableArea` decimal(10,2),\n\t`floor` varchar(50),\n\t`buildingName` varchar(200),\n\t`monthlyRent` decimal(15,0),\n\t`deposit` decimal(15,0),\n\t`managementFee` decimal(15,0),\n\t`floorPlanUrl` text,\n\t`photoUrls` json,\n\t`matchScore` int,\n\t`matchReasons` json,\n\t`status` enum('matched','shortlisted','viewing_scheduled','viewed','selected','rejected') NOT NULL DEFAULT 'matched',\n\t`clientNotes` text,\n\t`viewingDate` varchar(20),\n\t`externalSource` varchar(100),\n\t`externalId` varchar(200),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `realestate_matches_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `realestate_search_criteria` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientProjectId` int NOT NULL,\n\t`projectType` enum('relocation','renovation') NOT NULL,\n\t`desiredArea` decimal(10,2),\n\t`minArea` decimal(10,2),\n\t`maxArea` decimal(10,2),\n\t`desiredLocation` text,\n\t`budgetMin` decimal(15,0),\n\t`budgetMax` decimal(15,0),\n\t`moveInDate` varchar(20),\n\t`floorPreference` varchar(100),\n\t`buildingType` varchar(100),\n\t`parkingNeeded` int,\n\t`additionalRequirements` text,\n\t`status` enum('searching','matched','viewing','selected','closed') NOT NULL DEFAULT 'searching',\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `realestate_search_criteria_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `renderings` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`layoutId` int,\n\t`spaceType` varchar(100) NOT NULL,\n\t`spaceName` varchar(200),\n\t`prompt` text,\n\t`imageUrl` text,\n\t`thumbnailUrl` text,\n\t`style` varchar(100),\n\t`status` enum('pending','generating','done','error') NOT NULL DEFAULT 'pending',\n\t`error` text,\n\t`sortOrder` int DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `renderings_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_comparisons` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientProjectId` int,\n\t`userId` int,\n\t`traditionalCost` int DEFAULT 0,\n\t`rewallCost` int DEFAULT 0,\n\t`savingsAmount` int DEFAULT 0,\n\t`savingsPercent` int DEFAULT 0,\n\t`comparisonDetails` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `rewall_comparisons_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_inventory` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`productId` int NOT NULL,\n\t`warehouseLocation` varchar(200),\n\t`quantity` int NOT NULL DEFAULT 0,\n\t`reservedQuantity` int NOT NULL DEFAULT 0,\n\t`lastRestockedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `rewall_inventory_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_pricing` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`productId` int NOT NULL,\n\t`pricingType` enum('daily','weekly','monthly','purchase') NOT NULL DEFAULT 'monthly',\n\t`price` int NOT NULL DEFAULT 0,\n\t`discountPercent` int DEFAULT 0,\n\t`validFrom` timestamp,\n\t`validTo` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `rewall_pricing_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_products` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`sku` varchar(100),\n\t`category` varchar(100),\n\t`description` text,\n\t`specifications` json,\n\t`pricePerUnit` decimal(15,0),\n\t`unit` varchar(50),\n\t`imageUrls` json,\n\t`isActive` tinyint NOT NULL DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `rewall_products_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_reservation_items` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`reservationId` int NOT NULL,\n\t`productId` int NOT NULL,\n\t`quantity` int NOT NULL DEFAULT 1,\n\t`unitPrice` int NOT NULL DEFAULT 0,\n\t`subtotal` int NOT NULL DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `rewall_reservation_items_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_reservations` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientProjectId` int,\n\t`userId` int NOT NULL,\n\t`reservationStatus` enum('draft','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'draft',\n\t`installDate` varchar(10),\n\t`returnDate` varchar(10),\n\t`totalAmount` int DEFAULT 0,\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `rewall_reservations_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rewall_subscriptions` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`clientProjectId` int,\n\t`clientUserId` int,\n\t`plan` enum('purchase','lease','rental') NOT NULL DEFAULT 'rental',\n\t`monthlyFee` decimal(15,0),\n\t`contractMonths` int,\n\t`totalValue` decimal(15,0),\n\t`status` enum('draft','active','paused','cancelled','expired') NOT NULL DEFAULT 'draft',\n\t`startDate` varchar(20),\n\t`endDate` varchar(20),\n\t`items` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `rewall_subscriptions_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rfp_data` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`collectionMethod` enum('form','ai_generator','chatbot') NOT NULL DEFAULT 'form',\n\t`companyName` varchar(200),\n\t`industry` varchar(100),\n\t`foundedYear` int,\n\t`projectType` enum('new_office','relocation','renovation','expansion'),\n\t`currentAddress` text,\n\t`newAddress` text,\n\t`totalArea` varchar(50),\n\t`currentHeadcount` int,\n\t`plannedHeadcount1y` int,\n\t`plannedHeadcount3y` int,\n\t`departments` json,\n\t`spaceRequirements` json,\n\t`preferredStyle` varchar(100),\n\t`brandColors` json,\n\t`brandGuidelineUrl` text,\n\t`referenceImages` json,\n\t`referenceUrls` json,\n\t`preferredMaterials` json,\n\t`lightingPreference` varchar(200),\n\t`avItRequirements` text,\n\t`networkInfra` text,\n\t`securitySystem` text,\n\t`acousticPrivacy` varchar(100),\n\t`hvacRequirements` text,\n\t`esgRequirements` text,\n\t`budgetRange` varchar(100),\n\t`budgetInclDesign` enum('yes','no','separate'),\n\t`priorityOrder` varchar(200),\n\t`desiredStartDate` timestamp,\n\t`desiredEndDate` timestamp,\n\t`occupiedDuringWork` enum('yes','no','partial'),\n\t`buildingRestrictions` text,\n\t`reuseExistingFurniture` enum('yes','no','partial'),\n\t`specialRequests` text,\n\t`competitorBenchmarks` text,\n\t`aiSummary` text,\n\t`completionRate` int DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `rfp_data_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `rfq_requests` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`purchaseOrderId` int NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`itemIds` json,\n\t`status` enum('sent','viewed','quoted','selected','not_selected','expired') NOT NULL DEFAULT 'sent',\n\t`quotedItems` json,\n\t`quotedTotal` decimal(15,0),\n\t`quotedAt` timestamp,\n\t`token` varchar(64) NOT NULL,\n\t`expiresAt` timestamp,\n\t`sentAt` timestamp,\n\t`viewedAt` timestamp,\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `rfq_requests_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `rfq_requests_token_unique` UNIQUE(`token`)\n)",
  "CREATE TABLE IF NOT EXISTS `sensor_api_keys` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`name` varchar(100) NOT NULL,\n\t`apiKey` varchar(64) NOT NULL,\n\t`active` enum('yes','no') NOT NULL DEFAULT 'yes',\n\t`lastUsedAt` timestamp,\n\t`requestCount` int NOT NULL DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `sensor_api_keys_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `sensor_api_keys_apiKey_unique` UNIQUE(`apiKey`)\n)",
  "CREATE TABLE IF NOT EXISTS `sensor_data` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`sensorId` int NOT NULL,\n\t`projectId` int NOT NULL,\n\t`value` varchar(50) NOT NULL,\n\t`recordedAt` timestamp NOT NULL,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `sensor_data_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `sensors` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`name` varchar(100) NOT NULL,\n\t`type` enum('temperature','humidity','illuminance','co2','noise','occupancy','motion','air_quality','power') NOT NULL,\n\t`unit` varchar(20),\n\t`posX` int,\n\t`posY` int,\n\t`zone` varchar(100),\n\t`deviceId` varchar(100),\n\t`active` enum('yes','no') NOT NULL DEFAULT 'yes',\n\t`metadata` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `sensors_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `space_analysis` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`zone` varchar(100),\n\t`analysisType` enum('occupancy_pattern','environmental','energy','comfort','traffic_flow') NOT NULL,\n\t`summary` text,\n\t`dataJson` json,\n\t`recommendations` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `space_analysis_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `space_projects` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`client` varchar(200),\n\t`location` varchar(300),\n\t`area` varchar(50),\n\t`floorPlanUrl` text,\n\t`floorPlanWidth` int,\n\t`floorPlanHeight` int,\n\t`description` text,\n\t`status` enum('setup','collecting','analyzing','completed') NOT NULL DEFAULT 'setup',\n\t`analysisReport` json,\n\t`startDate` timestamp,\n\t`endDate` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `space_projects_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `space_zones` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`name` varchar(100) NOT NULL,\n\t`color` varchar(20) DEFAULT '#3b82f6',\n\t`polygon` json,\n\t`zoneType` enum('office','meeting','corridor','lounge','restroom','kitchen','storage','other') DEFAULT 'office',\n\t`capacity` int,\n\t`description` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `space_zones_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `staff_applications` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(200) NOT NULL,\n\t`email` varchar(320) NOT NULL,\n\t`phone` varchar(30),\n\t`department` enum('design','construction','accounting','management','sales','none') DEFAULT 'none',\n\t`message` text,\n\t`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',\n\t`reviewedByUserId` int,\n\t`reviewedAt` timestamp,\n\t`rejectReason` text,\n\t`createdUserId` int,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `staff_applications_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `staff_invitations` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`email` varchar(320) NOT NULL,\n\t`invitedByUserId` int NOT NULL,\n\t`token` varchar(128) NOT NULL,\n\t`department` enum('design','construction','accounting','management','sales','none') DEFAULT 'none',\n\t`opsRole` enum('pm','designer','site_manager','accountant','director','staff') DEFAULT 'staff',\n\t`status` enum('pending','accepted','expired','cancelled') NOT NULL DEFAULT 'pending',\n\t`acceptedUserId` int,\n\t`acceptedAt` timestamp,\n\t`expiresAt` timestamp NOT NULL,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `staff_invitations_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `staff_invitations_token_unique` UNIQUE(`token`)\n)",
  "CREATE TABLE IF NOT EXISTS `style_recommendations` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`sessionId` varchar(64) NOT NULL,\n\t`industry` varchar(100),\n\t`teamSize` varchar(50),\n\t`mood` varchar(100),\n\t`budget` varchar(50),\n\t`priorities` json,\n\t`resultJson` json,\n\t`imageUrl` text,\n\t`contactEmail` varchar(320),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `style_recommendations_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `sub_contracts` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`tradeCategoryId` int NOT NULL,\n\t`templateId` int,\n\t`contractNumber` varchar(50) NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`content` longtext NOT NULL,\n\t`partyA` varchar(200) NOT NULL DEFAULT '주식회사 고감도',\n\t`partyB` varchar(200) NOT NULL,\n\t`startDate` varchar(20) NOT NULL,\n\t`endDate` varchar(20) NOT NULL,\n\t`partyASignatureUrl` text,\n\t`partyASignatureKey` varchar(500),\n\t`partyBSignatureUrl` text,\n\t`partyBSignatureKey` varchar(500),\n\t`partyASignedAt` timestamp,\n\t`partyBSignedAt` timestamp,\n\t`partyASignedBy` int,\n\t`partyBSignerName` varchar(100),\n\t`pdfUrl` text,\n\t`pdfKey` varchar(500),\n\t`status` enum('draft','pending_b','pending_a','active','expired','terminated') NOT NULL DEFAULT 'draft',\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `sub_contracts_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `sub_registration_requests` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`companyName` varchar(200) NOT NULL,\n\t`businessNumber` varchar(20),\n\t`representativeName` varchar(100),\n\t`contactName` varchar(100),\n\t`contactPhone` varchar(30),\n\t`contactEmail` varchar(320),\n\t`address` text,\n\t`tradeIds` json,\n\t`specialty` varchar(500),\n\t`bankName` varchar(100),\n\t`bankAccount` varchar(50),\n\t`bankHolder` varchar(100),\n\t`businessLicenseUrl` text,\n\t`businessLicenseKey` varchar(500),\n\t`status` enum('pending','staff_approved','approved','rejected') NOT NULL DEFAULT 'pending',\n\t`requestedBy` int NOT NULL,\n\t`requestedByName` varchar(100),\n\t`staffApprovedBy` int,\n\t`staffApprovedByName` varchar(100),\n\t`staffApprovedAt` timestamp,\n\t`staffComment` text,\n\t`adminApprovedBy` int,\n\t`adminApprovedByName` varchar(100),\n\t`adminApprovedAt` timestamp,\n\t`adminComment` text,\n\t`rejectedBy` int,\n\t`rejectedByName` varchar(100),\n\t`rejectedAt` timestamp,\n\t`rejectionReason` text,\n\t`subcontractorId` int,\n\t`notes` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `sub_registration_requests_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `subcontractor_trades` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`subcontractorId` int NOT NULL,\n\t`tradeCategoryId` int NOT NULL,\n\t`isPrimary` tinyint NOT NULL DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `subcontractor_trades_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `subscriber_segments` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(200) NOT NULL,\n\t`description` text,\n\t`color` varchar(20) DEFAULT '#b8860b',\n\t`filterConditions` json,\n\t`matchCount` int DEFAULT 0,\n\t`lastCalculatedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `subscriber_segments_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `subscriber_tags` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`subscriberId` int NOT NULL,\n\t`tag` varchar(100) NOT NULL,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `subscriber_tags_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `survey_analysis_reports` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`instanceId` int NOT NULL,\n\t`clientProjectId` int,\n\t`reportType` enum('initial_analysis','company_analysis','space_requirement','optimization') NOT NULL,\n\t`title` varchar(300) NOT NULL,\n\t`summary` text,\n\t`content` longtext NOT NULL,\n\t`insights` json,\n\t`spaceRequirements` json,\n\t`isBlurred` tinyint NOT NULL DEFAULT 1,\n\t`viewCount` int DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `survey_analysis_reports_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `survey_instances` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`templateId` int NOT NULL,\n\t`clientProjectId` int,\n\t`token` varchar(128) NOT NULL,\n\t`type` enum('initial_manager','company_wide','post_occupancy') NOT NULL,\n\t`recipientEmail` varchar(320),\n\t`recipientName` varchar(200),\n\t`status` enum('pending','sent','opened','in_progress','completed','expired') NOT NULL DEFAULT 'pending',\n\t`customQuestions` json,\n\t`responseCount` int DEFAULT 0,\n\t`sentAt` timestamp,\n\t`completedAt` timestamp,\n\t`expiresAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `survey_instances_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `survey_instances_token_unique` UNIQUE(`token`)\n)",
  "CREATE TABLE IF NOT EXISTS `survey_question_options` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`questionId` int NOT NULL,\n\t`optionText` varchar(500) NOT NULL,\n\t`optionValue` varchar(200),\n\t`sortOrder` int NOT NULL DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `survey_question_options_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `survey_questions` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`templateId` int NOT NULL,\n\t`sectionTitle` varchar(200),\n\t`questionText` text NOT NULL,\n\t`questionType` enum('single_choice','multiple_choice','scale','text','number','matrix') NOT NULL,\n\t`isRequired` tinyint NOT NULL DEFAULT 1,\n\t`sortOrder` int NOT NULL DEFAULT 0,\n\t`metadata` json,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `survey_questions_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `survey_responses` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`instanceId` int NOT NULL,\n\t`respondentName` varchar(200),\n\t`respondentEmail` varchar(320),\n\t`respondentDepartment` varchar(200),\n\t`respondentRole` varchar(200),\n\t`answers` json NOT NULL,\n\t`completedAt` timestamp,\n\t`ipAddress` varchar(50),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `survey_responses_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `survey_templates` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`type` enum('initial_manager','company_wide','post_occupancy','custom') NOT NULL,\n\t`description` text,\n\t`isDefault` tinyint DEFAULT 0,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdBy` int,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `survey_templates_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `tour_videos` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`title` varchar(300),\n\t`videoUrl` text,\n\t`thumbnailUrl` text,\n\t`duration` int,\n\t`renderingIds` json,\n\t`status` enum('pending','generating','done','error') NOT NULL DEFAULT 'pending',\n\t`error` text,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `tour_videos_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `trade_categories` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`name` varchar(100) NOT NULL,\n\t`code` varchar(20) NOT NULL,\n\t`description` text,\n\t`parentId` int,\n\t`sortOrder` int DEFAULT 0,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `trade_categories_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `trade_categories_code_unique` UNIQUE(`code`)\n)",
  "CREATE TABLE IF NOT EXISTS `trade_contract_templates` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`tradeCategoryId` int NOT NULL,\n\t`name` varchar(300) NOT NULL,\n\t`content` longtext NOT NULL,\n\t`validityMonths` int NOT NULL DEFAULT 12,\n\t`version` int DEFAULT 1,\n\t`isActive` tinyint NOT NULL DEFAULT 1,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `trade_contract_templates_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `vendor_quote_items` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`quoteId` int NOT NULL,\n\t`itemName` varchar(300) NOT NULL,\n\t`specification` text,\n\t`unit` varchar(50),\n\t`quantity` decimal(10,2),\n\t`unitPrice` decimal(15,0),\n\t`amount` decimal(15,0),\n\t`category` varchar(100),\n\t`materialCode` varchar(100),\n\t`sortOrder` int DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `vendor_quote_items_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `vendor_quotes` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`subcontractorId` int,\n\t`vendorName` varchar(200) NOT NULL,\n\t`vendorContact` varchar(200),\n\t`vendorEmail` varchar(320),\n\t`vendorPhone` varchar(30),\n\t`quoteNumber` varchar(100),\n\t`quoteDate` varchar(20),\n\t`validUntil` varchar(20),\n\t`fileUrl` text,\n\t`fileKey` varchar(500),\n\t`fileName` varchar(300),\n\t`fileType` varchar(50),\n\t`totalAmount` decimal(15,0),\n\t`vatAmount` decimal(15,0),\n\t`aiParsed` tinyint DEFAULT 0,\n\t`aiParsedData` json,\n\t`status` enum('submitted','reviewing','accepted','rejected','revised') NOT NULL DEFAULT 'submitted',\n\t`reviewNotes` text,\n\t`category` varchar(100),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `vendor_quotes_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `work_surveys` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`respondentName` varchar(100) NOT NULL,\n\t`respondentRole` varchar(100),\n\t`respondentEmail` varchar(320),\n\t`workStyle` enum('collaborative','focused','hybrid','flexible'),\n\t`remoteWorkRatio` int,\n\t`meetingFrequency` enum('rarely','few_weekly','daily','very_frequent'),\n\t`privateOfficeCount` int,\n\t`meetingRoomCount` int,\n\t`needsLounge` tinyint,\n\t`needsCafeteria` tinyint,\n\t`needsPhoneBooth` tinyint,\n\t`needsLibrary` tinyint,\n\t`needsGym` tinyint,\n\t`needsNapRoom` tinyint,\n\t`specialSpaces` text,\n\t`designStyle` enum('modern','minimal','warm','industrial','natural','luxury','creative'),\n\t`colorPreference` varchar(200),\n\t`brandColors` varchar(200),\n\t`inspirationNotes` text,\n\t`currentPainPoints` json,\n\t`priorityAreas` json,\n\t`acRequirements` text,\n\t`lightingPreference` enum('natural','warm','cool','mixed'),\n\t`noiseControl` enum('critical','important','moderate','not_important'),\n\t`storageNeeds` enum('minimal','moderate','extensive'),\n\t`techRequirements` text,\n\t`budgetPriority` enum('cost_saving','balanced','quality_first'),\n\t`timelineUrgency` enum('flexible','within_6months','within_3months','urgent'),\n\t`additionalNotes` text,\n\t`completedAt` timestamp,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `work_surveys_id` PRIMARY KEY(`id`)\n)",
  "CREATE TABLE IF NOT EXISTS `workspace_journeys` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`sessionId` varchar(64) NOT NULL,\n\t`currentStep` enum('survey','floor_plan','generating','report_ready','signup_prompted','converted') NOT NULL DEFAULT 'survey',\n\t`companyName` varchar(200),\n\t`contactName` varchar(100),\n\t`contactEmail` varchar(320),\n\t`contactPhone` varchar(50),\n\t`employeeCount` int,\n\t`officeSizePyeong` int,\n\t`workStyle` enum('collaborative','focused','hybrid','flexible'),\n\t`remoteWorkRatio` int,\n\t`meetingFrequency` enum('rarely','few_weekly','daily','very_frequent'),\n\t`painPoints` json,\n\t`desiredSpaces` json,\n\t`designStyle` enum('modern','minimal','warm','industrial','natural','luxury','creative'),\n\t`budgetRange` varchar(50),\n\t`priority` enum('design','functionality','cost','balanced'),\n\t`timelineUrgency` enum('flexible','within_6months','within_3months','urgent'),\n\t`additionalNotes` text,\n\t`surveyCompletedAt` timestamp,\n\t`floorPlanType` enum('blank_template','existing_upload','skipped'),\n\t`floorPlanFileKey` varchar(500),\n\t`floorPlanFileUrl` varchar(1000),\n\t`floorPlanFileName` varchar(300),\n\t`blankTemplateType` varchar(50),\n\t`floorPlanAnalysis` json,\n\t`floorPlanUploadedAt` timestamp,\n\t`interviewQuestions` json,\n\t`analysisSummary` text,\n\t`aiGeneratedAt` timestamp,\n\t`reportToken` varchar(64),\n\t`reportPdfKey` varchar(500),\n\t`reportPdfUrl` varchar(1000),\n\t`reportEmailSentAt` timestamp,\n\t`reportViewedAt` timestamp,\n\t`companySurveyToken` varchar(64),\n\t`companySurveyResponseCount` int DEFAULT 0,\n\t`interviewResponses` json,\n\t`clientId` int,\n\t`convertedAt` timestamp,\n\t`utmSource` varchar(100),\n\t`utmMedium` varchar(100),\n\t`utmCampaign` varchar(100),\n\t`referrer` varchar(500),\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\t`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,\n\tCONSTRAINT `workspace_journeys_id` PRIMARY KEY(`id`),\n\tCONSTRAINT `workspace_journeys_sessionId_unique` UNIQUE(`sessionId`)\n)",
  "CREATE TABLE IF NOT EXISTS `zone_occupancy_stats` (\n\t`id` int AUTO_INCREMENT NOT NULL,\n\t`projectId` int NOT NULL,\n\t`zoneId` int NOT NULL,\n\t`bucketHour` timestamp NOT NULL,\n\t`avgOccupancy` int DEFAULT 0,\n\t`maxOccupancy` int DEFAULT 0,\n\t`totalMinutesOccupied` int DEFAULT 0,\n\t`enterCount` int DEFAULT 0,\n\t`exitCount` int DEFAULT 0,\n\t`createdAt` timestamp NOT NULL DEFAULT (now()),\n\tCONSTRAINT `zone_occupancy_stats_id` PRIMARY KEY(`id`)\n)",
];

export async function ensureExtendedTables(conn: Connection): Promise<void> {
  let created = 0;
  const failures: string[] = [];
  for (const ddl of EXTENDED_TABLE_DDL) {
    const name = ddl.match(/IF NOT EXISTS `([^`]+)`/)?.[1] ?? "?";
    try {
      await conn.query(ddl);
      created++;
    } catch (err: any) {
      failures.push(`${name}: ${err?.code ?? ""} ${err?.sqlMessage ?? err?.message ?? "unknown"}`);
    }
  }
  console.log(`[DB] Extended tables ensured (${created}/${EXTENDED_TABLE_DDL.length}).`);
  if (failures.length) {
    console.warn("[DB] Extended table failures:\n" + failures.join("\n"));
  }
}
